=== Alvarocotumba/vscode_DAM/Lenguaje de Marcas/ejercicio_final/data/data.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="cursos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="curso" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string"/>
                            <xs:element name="nivel" type="xs:string"/>
                            <xs:element name="horas" type="xs:integer"/>
                            <xs:element name="categoria" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Alvarocotumba/vscode_DAM/Lenguaje de Marcas/ejercicio_final/data/data.xml
<?xml version="1.0" encoding="UTF-8"?>

<cursos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="data.xsd">

    <curso id="c1">
    <titulo>HTML y CSS</titulo>
    <nivel>Principiante</nivel>
    <horas>50</horas>
    <categoria>Frontend</categoria>
</curso>

<curso id="c2">
    <titulo>Javascript para web</titulo>
    <nivel>Intermedio</nivel>
    <horas>80</horas>
    <categoria>Frontend</categoria>
</curso>

<curso id="c3">
    <titulo>Base de datos</titulo>
    <nivel>Principiante</nivel>
    <horas>40</horas>
    <categoria>Backend</categoria>
</curso>

<curso id="c4">
    <titulo>Programación en java</titulo>
    <nivel>Intermedio</nivel>
    <horas>50</horas>
    <categoria>Backend</categoria>
</curso>

</cursos>
